name: Backend CD
# postgresql://garapexpress:Ax4gYROdXcviIL1w1V2FXZsAwfOS5kDH@dpg-d75q836slomc73e02mb0-a/garapexpress
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Render
        run: |
          render Render deploy garapexpress-backend
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}